### PR TITLE
1 register new journey

### LINKED ISSUE #1: 1-Register-new-journey('meeto')
As a person,
So that I can find travelling companions to make my journey cheaper,
I would like to be able to register a journey.

### PR DESCRIPTION
**Pull request by prSathan**
closes #1

### CODE REVIEW

**Review by jjadeseravla — COMMENTED** [review]
💃 
🐤 
kye deleted 'HEllo worl!'

**Review by KyeBracey — APPROVED** [review]
:shipit:

**Comment by jjadeseravla** [comment]
:shipit:

**Review by marioribeiro — APPROVED** [review]
I'm happy

**Pull request merged**
